name: CI

on:
    push:
        branches:
            - master

jobs:
    lint:
        name: Lint and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Aftman
              uses: ok-nick/setup-aftman@v0.3.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate Roblox std file
              run: selene generate-roblox-std

            - name: Run Selene
              run: selene V5Source

            - name: Build
              run: rojo build -o module.rbxm .github/upload.project.json

            - name: Upload
              uses: fjogeleit/http-request-action@v1
              with:
                  url: "${{ secrets.UPLOAD_URL }}"
                  method: "POST"
                  file: "module.rbxm"
                  customHeaders: '{ "secret": "${{ secrets.SECRET }}" }'
                  timeout: 10000
